### ISSUE TITLE
Use of undeclared identifier 'LOG_ASYNC_ENABLED'

### ISSUE THREAD

**Issue by ckrey** [CocoaLumberjack/CocoaLumberjack#778]
![bildschirmfoto 2016-09-22 um 16 03 42](https://cloud.githubusercontent.com/assets/4027289/18751152/496eb4b0-80de-11e6-8893-0395a7bf82ad.png)
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](https://github.com/CocoaLumberjack/CocoaLumberjack#documentation) or [CocoaDocs](cocoadocs.org/docsets/CocoaLumberjack)
- [x] I have searched for a similar issue in the [project](https://github.com/CocoaLumberjack/CocoaLumberjack/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | ios |
| Platform Version | 10 |
| CocoaLumberjack Version | 3.0.0 / 2.4.0 |
| Integration Method | cocoapods |
| Xcode Version | Xcode 8.0 |
| Repro rate | all the time (100%) |
| Demo project link | n/a |
### Issue Description and Steps

after upgrading via pod update from 2.3 to 3.0 / 2.4

**Comment by georgepoenaru** [comment]
+1 

@ckrey  I use your MQTTClient in Xcode 8 with Swift3 and I also trying to figure out why it does happening this. No cache clearing do the work.

**Comment by ckrey** [comment]
it works if you use Lumberjack 2.3.x

**Comment by max-potapov** [comment]
Reproduced with project which contains mixed objc+swift code.

**Comment by georgepoenaru** [comment]
@ckrey Yes, this have resolved.

@max-potapov  Unfortunately your workaround doesn't fix the ObjC dependencies libs for Swift proj. So in Swift projects with ObjC dependencies that use lumberjack via cocoapods you're out of control of these workarounds. Or even worse when you try to build Swift lib on top of ObjC lib.

**Comment by szpako1** [comment]
I've faced the same using [Lock framework](https://github.com/auth0/Lock.iOS-OSX) that uses CocoaLumberjack as dependency in podspec. Do you plan to resolve that?

**Comment by sushichop** [comment]
Hi guys, I pushed PR(#784). This PR should solve the issue.

@CocoaLumberjack
Could you review my PR?

**Comment by levigroker** [comment]
I'm seeing this against the 3.0 spec... do we know when the mentioned pull request will make it into a published version of the pod?

**Comment by schartyom** [comment]
Still reproduces in objc+swift project

**Comment by bpoplauschi** [comment]
Probably fixed by #784
