### ISSUE TITLE
Use of undeclared identifier ‘ddLogLevel’ with 2.0.1

### ISSUE THREAD

**Issue by stephent** [CocoaLumberjack/CocoaLumberjack#577]
The following code works fine with CocoaPods 2.0.0, but fails to compile with "Use of undeclared identifier ‘ddLogLevel’" on the line starting DDLogInfo under 2.0.1:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    
    DDLogLevel globalLogLevel;
#ifdef DEBUG
    globalLogLevel = DDLogLevelDebug;
#else
    globalLogLevel = DDLogLevelInfo;
#endif
    
    DDFileLogger *fileLogger = [[DDFileLogger alloc] init];
    fileLogger.maximumFileSize = (1024 * 64); // 64 KByte
    fileLogger.logFileManager.maximumNumberOfLogFiles = 1;
    [fileLogger rollLogFileWithCompletionBlock:nil];
    [DDLog addLogger:fileLogger withLevel: globalLogLevel];
    
    DDLogInfo(@"application:didFinishLaunchingWithOptions: %@", launchOptions.description);
    
    return YES;
}

```

I'm sure there's something obvious I'm missing, but I can't see what. 

(I'm looking to have a global log level which I can change at run time. I don't want per file log levels.)

Any pointers?

**Comment by DD-P** [comment]
This sounds like the issue being discussed in #542.

**Comment by rivera-ernesto** [comment]
Yes. Please do a quick search before opening new issues.

**Comment by stephent** [comment]
@rivera-ernesto I did, of course. For some reason it didn't show.

**Comment by rivera-ernesto** [comment]
Sometimes issue descriptions and titles can be hard to understand ;)

**Comment by stephent** [comment]
You're a funny guy.
